on: [push]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build documentation
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: ./Doxyfile
